version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    # image: 
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      - /app/public
      - /app/prisma
    # environment:
    #   DATABASE_URL: 