version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    # image: nextjs-prisma-docker_nextjs:latest
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
      - ./entrypoint:/app/entrypoint
    # environment:
    #   DATABASE_URL: